title: Console Gaming
author: dhruv2365
email: dhruv2365@gamil.com
description: > # this means to ignore newlines until "baseurl:"
  I will blog about gaming on console!
# social links
twitter_username: dhruv2365 # DO NOT include the @ character, or else the build will fail!
github_username:  dhruv2365 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
